In [3]:
t= (3,)

In [4]:
type(t)

tuple

In [5]:
str(range(10))

'range(0, 10)'

In [6]:
sum([i for i in range (10) if i%2 != 0])

25

In [7]:
sum([i for i in range(10) if i%2 == 1])

25

In [8]:
x= [0,10,15,7,8]
x[0]

0

In [10]:
[x[1]]*4

[10, 10, 10, 10]

In [13]:
def moving_window_average(x, n_neighbors=1):
    n = len(x)
    width = n_neighbors*2 + 1
    x = [x[0]]*n_neighbors + x + [x[-1]]*n_neighbors
    return [sum(x[a:(a+width)]) / width for a in range(n)]

x = [0,10,5,3,1,5]
print((moving_window_average(x, 1)))


[3.3333333333333335, 5.0, 6.0, 3.0, 3.0, 3.6666666666666665]


In [31]:
import numpy as np
s = np.ndarray((3,3))
s = np.zeros((3,3))
s[1][1],s[0][0] = 2,5
s 

array([[5., 0., 0.],
       [0., 2., 0.],
       [0., 0., 0.]])

In [37]:
ls =[] 
ls= [np.where(s>0)]
ls

[(array([0, 1], dtype=int64), array([0, 1], dtype=int64))]

In [38]:
a = np.array([[0, 1, 2], [0, 2, 4],[0, 3, 6]])
np.where(a < 4, a, -1) 

array([[ 0,  1,  2],
       [ 0,  2, -1],
       [ 0,  3, -1]])

In [39]:
list_of_coordinates = [(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]
list_of_coordinates

[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [40]:
import random
x = random.choice(list_of_coordinates)
x

(1, 0)

In [47]:
a[x] = 2
a[x]

2

In [53]:
import numpy as np
boar = np.ndarray((3,3))
def create_boar():
    boar = [[0 for j in range(3)] for i in range(3)]
    return boar
create_boar()
boar

array([[5., 0., 0.],
       [0., 2., 0.],
       [0., 0., 0.]])

In [55]:
import numpy as np
b = np.ndarray((4,4))
def b_z():
    b = [[0 for i in range(4)] for i in range(4)]
    return b
b

array([[4.67296746e-307, 1.69121096e-306, 1.24610994e-306,
        1.11256817e-306],
       [1.06811422e-306, 1.42417221e-306, 1.11260619e-306,
        8.90094053e-307],
       [1.86919378e-306, 1.06809792e-306, 1.37962456e-306,
        1.69111861e-306],
       [1.78020169e-306, 1.37961777e-306, 7.56599807e-307,
        7.56599806e-307]])

In [77]:
ls= [2,3,9,4,6,5]
p = [True for i in range(6) if ls[i]>3]
p


[True, True, True, True]

In [91]:
import numpy as np
x= np.ndarray((3,3))
ls = [(0, 0), (0, 2), (1, 1), (2, 0), (2, 2)]
for i in ls:
    print(x[i])

5.0
0.0
2.0
0.0
0.0
